Repository boostcampwm-2024/web27-Preview, pull requests merged in 2024-12, with the labels that each got.

#291 [Refactor] 질문지 리스트 페이지 리팩토링 및 스크랩, 공유하기 기능
  frontend/src/api/question-list/getQuestionList.ts
  frontend/src/components/common/Button/index.tsx
  frontend/src/components/questions/QuestionsPreviewCard.tsx
  frontend/src/components/questions/detail/ButtonSection.tsx/index.tsx
  frontend/src/components/questions/detail/QuestionList.tsx/QuestionItem.tsx
  frontend/src/components/questions/detail/QuestionList.tsx/index.tsx
  frontend/src/components/questions/detail/QuestionTitle.tsx/index.tsx
  frontend/src/hooks/api/useGetQuestionList.ts
  frontend/src/pages/CreateQuestionPage.tsx
  frontend/src/pages/QuestionDetailPage.tsx
  frontend/src/pages/QuestionDetailPage/QuestionDetailPage.tsx
  frontend/src/pages/QuestionDetailPage/api/scrapAPI.ts
  frontend/src/pages/QuestionListPage.tsx
  frontend/src/pages/QuestionListPage/QuestionListPage.tsx
  frontend/src/pages/QuestionListPage/hooks/useCategory.ts
  frontend/src/pages/QuestionListPage/types/QuestionList.d.ts
  frontend/src/pages/QuestionListPage/view/QuestionsPreviewList.tsx
  frontend/src/pages/SessionListPage/view/list/SessionList.tsx
  frontend/src/routes.tsx
Labels: 🎁 Refactoring

#293 [Refactor] 비디오 레이아웃 동적으로 조정 | 세션 페이지 일부 디자인 변경
  frontend/package.json
  frontend/src/components/common/Modal/index.tsx
  frontend/src/components/common/ToolTip.tsx
  frontend/src/components/mypage/ButtonSection.tsx
  frontend/src/components/mypage/QuestionList/QuestionItem/index.tsx
  frontend/src/components/session/CommonTools.tsx
  frontend/src/components/session/DisplayMediaStream.tsx
  frontend/src/components/session/HostOnlyTools.tsx
  frontend/src/components/session/SessionHeader.tsx
  frontend/src/components/session/Toolbar/CommonTools.tsx
  frontend/src/components/session/Toolbar/HostOnlyTools.tsx
  frontend/src/components/session/VideoContainer.tsx
  frontend/src/hooks/api/useGetQuestionContent.ts
  frontend/src/pages/MyPage/view/ProfileEditModal.tsx
  frontend/src/pages/SessionPage.tsx
  frontend/src/pages/SessionPage/hooks/useMediaDevices.ts
  frontend/src/pages/SessionPage/hooks/useMediaStreamCleanup.ts
  frontend/src/pages/SessionPage/hooks/usePeerConnection.ts
  frontend/src/pages/SessionPage/hooks/usePeerConnectionCleanup.ts
  frontend/src/pages/SessionPage/hooks/useReaction.ts
  frontend/src/pages/SessionPage/hooks/useSession.ts
  frontend/src/pages/SessionPage/hooks/useSocketEvents.ts
  frontend/src/pages/SessionPage/hooks/useStudy.ts
  frontend/src/pages/SessionPage/index.tsx
  frontend/src/pages/SessionPage/view/SessionHeader.tsx
  frontend/src/pages/SessionPage/view/SessionSidebar.tsx
  frontend/src/pages/SessionPage/view/SessionToolbar.tsx
  frontend/src/pages/SessionPage/view/SidebarContainer.tsx
  frontend/src/pages/SessionPage/view/VideoLayout.tsx
  frontend/src/routes.tsx
  frontend/src/stores/useModalStore.ts
  frontend/tailwind.config.js
Labels: 🎁 Refactoring

#296 [Fix] 명세서에 맞게 로그인 타입 반환값 수정
  backend/src/user/user.service.ts
Labels: 🐛 Bug Fix

#294 [Fix] 중복 닉네임 요청 시 400번 반환되도록 수정
  backend/src/user/user.repository.ts
  backend/src/user/user.service.ts
Labels: 🐛 Bug Fix, 로그인 회원가입 기능

#295 [Feat] 비디오 프로필 오버레이 구현 및 index.html og-image 수정
  frontend/index.html
  frontend/public/preview-banner.png
  frontend/src/components/session/VideoContainer.tsx
  frontend/src/components/session/VideoProfileOverlay.tsx
  frontend/src/components/session/VideoReactionBox.tsx
  pnpm-lock.yaml
Labels: ✨ Feature

#299 [Docs] 리드미 업데이트
  README.md
Labels: 📄 Documents

#297 [Fix] 로그인 필드 중복 에러 처리
  frontend/src/pages/Login/hooks/useValidate.ts
  frontend/src/pages/Login/view/DefaultAuthFormContainer.tsx
Labels: 🐛 Bug Fix

#301 [Feat] 마이페이지 회원정보 수정
  frontend/src/api/user/editMyInfo.ts
  frontend/src/api/user/getMyInfo.ts
  frontend/src/components/common/Button/index.tsx
  frontend/src/components/common/CategorySelector/index.tsx
  frontend/src/components/common/Pagination/index.tsx
  frontend/src/components/common/Select.tsx
  frontend/src/components/common/TitleInput/index.tsx
  frontend/src/components/mypage/ButtonSection.tsx
  frontend/src/components/mypage/PasswordInput.tsx
  frontend/src/components/mypage/ProfileIcon.tsx
  frontend/src/components/questions/create/QuestionForm/CategorySection/index.tsx
  frontend/src/components/questions/create/QuestionForm/QuestionInputSection/QuestionInput.tsx
  frontend/src/components/questions/create/QuestionForm/TitleSection/index.tsx
  frontend/src/components/questions/create/QuestionForm/index.tsx
  frontend/src/components/sessions/create/SessionForm/CategorySection/index.tsx
  frontend/src/hooks/__test__/useSession.test.ts
  frontend/src/pages/MyPage/index.tsx
  frontend/src/pages/MyPage/view/Profile.tsx
  frontend/src/pages/MyPage/view/ProfileEditModal.tsx
  frontend/src/pages/MyPage/view/QuestionSection.tsx
  frontend/src/pages/MyPage/view/index.tsx
  frontend/src/pages/QuestionDetailPage/QuestionDetailPage.tsx
  frontend/src/pages/QuestionListPage/QuestionListPage.tsx
  frontend/src/pages/SessionListPage/SessionListPage.tsx
  frontend/src/pages/SessionPage/hooks/useReaction.ts
  frontend/src/stores/useUserStore.ts
Labels: ✨ Feature

#298 [Refactor] question-list 모듈 리팩토링 및 pagination 구현
  backend/package.json
  backend/src/app.module.ts
  backend/src/config/typeorm.config.ts
  backend/src/question-list/dto/paginate-meta.dto.ts
  backend/src/question-list/dto/paginate-query.dto.ts
  backend/src/question-list/dto/paginate.dto.ts
  backend/src/question-list/dto/question-list-contents.dto.ts
  backend/src/question-list/entity/category.entity.ts
  backend/src/question-list/entity/question-list.entity.ts
  backend/src/question-list/entity/question.entity.ts
  backend/src/question-list/question-list.controller.ts
  backend/src/question-list/question-list.module.ts
  backend/src/question-list/question-list.repository.ts
  backend/src/question-list/question-list.service.ts
  backend/src/question-list/repository/category.repository.ts
  backend/src/question-list/repository/question-list.repository.ts
  backend/src/question-list/repository/question.respository.ts
  backend/src/question/question.module.ts
  backend/src/room/room.module.ts
  backend/src/room/services/room-create.service.ts
  backend/src/room/services/room-join.service.ts
  backend/src/user/dto/user.dto.ts
  backend/src/user/user.entity.ts
Labels: 🐛 Bug Fix, 🎁 Refactoring

#302 [Fix] 빌드에러 수정
  frontend/src/components/common/TitleInput/index.tsx
  frontend/src/components/sessions/create/SessionForm/TitleSection/index.tsx
  frontend/src/pages/SessionPage/hooks/usePeerConnection.ts
Labels: 🐛 Bug Fix

#303 [Fix] 빌드 에러 수정
  frontend/src/components/common/TitleInput/index.tsx
  frontend/src/components/sessions/create/SessionForm/TitleSection/index.tsx
  frontend/src/pages/SessionPage/hooks/usePeerConnection.ts
Labels: 🐛 Bug Fix

#305 [Fix] Passport JWT 사용 중지 및 에러 던지지 않도록 수정
  backend/package.json
  backend/src/auth/auth.controller.ts
  backend/src/auth/jwt/jwt.decorator.ts
  backend/src/auth/jwt/strategy/access-token.strategy.ts
  backend/src/user/user.controller.ts
  pnpm-lock.yaml
Labels: 🐛 Bug Fix

#307 [Refactor] 로그인 throttle 최적화, OS기본 다크모드 비활성화, robots.txt 추가, 비밀번호 보기 기능 추가
  frontend/public/robots.txt
  frontend/src/components/questions/QuestionsPreviewCard.tsx
  frontend/src/index.css
  frontend/src/pages/Login/LoginPage.tsx
  frontend/src/pages/Login/hooks/useValidate.ts
  frontend/src/pages/Login/view/DefaultAuthFormContainer.tsx
Labels: 🎁 Refactoring

#308 [Feat] 말하는 사람의 비디오에 테두리 추가
  frontend/src/components/session/VideoContainer.tsx
  frontend/src/pages/SessionPage/hooks/useAudioDetector.ts
  frontend/src/pages/SessionPage/hooks/usePeerConnection.ts
  frontend/src/pages/SessionPage/hooks/useSession.ts
  frontend/src/pages/SessionPage/index.tsx
  frontend/src/pages/SessionPage/view/VideoLayout.tsx
Labels: ✨ Feature

#310 [Refactor] base Repository 상속 & 트랜잭션 범위 최소화
  backend/src/app.module.ts
  backend/src/question-list/dto/question-list.dto.ts
  backend/src/question-list/question-list.service.ts
  backend/src/question-list/repository/category.repository.ts
  backend/src/question-list/repository/question-list.repository.ts
  backend/src/question-list/repository/question.respository.ts
  backend/src/question/question.module.ts
  backend/src/room/services/room-create.service.ts
Labels: 🎁 Refactoring

#313 [Refactor] 질문지 리스트페이지 페이지네이션 적용, Tab추가, 생성 폼 오류 해결
  frontend/package-lock.json
  frontend/src/api/question-list/getQuestionList.ts
  frontend/src/api/question-list/getScrapQuestionList.ts
  frontend/src/components/common/Select/CategorySelect.tsx
  frontend/src/components/questions/QuestionsPreviewCard.tsx
  frontend/src/hooks/api/useGetQuestionList.ts
  frontend/src/pages/CreateQuestionPage/CreateQuestionPage.tsx
  frontend/src/pages/IntroPage/IntroPage.tsx
  frontend/src/pages/QuestionDetailPage/QuestionDetailPage.tsx
  frontend/src/pages/QuestionListPage/QuestionListPage.tsx
  frontend/src/pages/QuestionListPage/view/QuestionListHeader.tsx
  frontend/src/pages/QuestionListPage/view/QuestionsPreviewList.tsx
  frontend/src/pages/QuestionListPage/view/Tabs.tsx
  frontend/vite.config.ts
Labels: 🎁 Refactoring

#314 [Feat] 401에러에 대한 처리 axios 인터셉터 사용, 최소 질문 길이 5자로 수정
  backend/src/auth/auth.controller.ts
  backend/src/auth/jwt/jwt.service.ts
  backend/src/auth/jwt/strategy/refresh-token.strategy.ts
  frontend/src/api/config/axios.ts
  frontend/src/api/user/auth.ts
  frontend/src/components/questions/create/QuestionInputSection/QuestionInput.tsx
  frontend/src/pages/Login/AuthCallbackPage.tsx
  frontend/src/pages/Login/hooks/useValidate.ts
  frontend/src/pages/Login/view/OAuthContainer.tsx
  frontend/src/pages/MyPage/MyPage.tsx
  frontend/src/pages/QuestionListPage/view/Tabs.tsx
  frontend/src/routes.tsx
Labels: ✨ Feature

#317 [Feat] `GET /api/rooms` 요청에 대해 필터링 추가 옵션 제공
  backend/src/room/dto/all-room.dto.ts
  backend/src/room/room.controller.ts
  backend/src/room/services/room.service.ts
Labels: ✨ Feature, 스터디 세션 기능

#315 [Design] 스터디 채널 디자인 변경
  frontend/src/api/session-list/getSessionList.ts
  frontend/src/components/common/Input/SearchBar.tsx
  frontend/src/components/sessions/create/SessionForm/ListSelectModal/CategoryTab/Category.tsx
  frontend/src/components/sessions/create/SessionForm/ListSelectModal/CategoryTab/index.tsx
  frontend/src/components/sessions/create/SessionForm/ListSelectModal/QuestionList/QuestionItem.tsx
  frontend/src/components/sessions/create/SessionForm/ListSelectModal/index.tsx
  frontend/src/components/sessions/create/SessionForm/ParticipantSection/ParticpantButton.tsx
  frontend/src/pages/CreateQuestionPage/CreateQuestionPage.tsx
  frontend/src/pages/CreateSessionPage/CreateSessionPage.tsx
  frontend/src/pages/SessionListPage/SessionListPage.tsx
  frontend/src/pages/SessionListPage/api/useGetSessionList.ts
  frontend/src/pages/SessionListPage/view/SessionCard.tsx
  frontend/src/pages/SessionListPage/view/SessionList.tsx
  frontend/src/pages/SessionListPage/view/Tab.tsx
  frontend/src/pages/SessionListPage/view/TabContainer.tsx
  frontend/tailwind.config.js
Labels: 🎨 Design

#318 [Feat] inProgress에 따라 스터디 채널 탭 설정
  frontend/src/api/session-list/getSessionList.ts
  frontend/src/components/common/Animate/NotFound.tsx
  frontend/src/pages/SessionListPage/SessionListPage.tsx
  frontend/src/pages/SessionListPage/api/useGetSessionList.ts
  frontend/src/pages/SessionListPage/view/SessionList.tsx
  frontend/src/pages/SessionListPage/view/Tab.tsx
  frontend/src/pages/SessionListPage/view/TabContainer.tsx
Labels: ✨ Feature

#319 [Fix] 리액션 안보이던 문제, 미디어 상태 공유 안되던 문제 해결
  frontend/src/components/session/VideoReactionBox.tsx
  frontend/src/pages/SessionPage/hooks/usePeerConnection.ts
  frontend/src/pages/SessionPage/index.tsx
  frontend/src/pages/SessionPage/session/usePeerConnection.ts
  frontend/src/pages/SessionPage/session/useReaction.ts
Labels: 🐛 Bug Fix

#316 [Refactor] 스터디 세션 부분 리팩토링
  backend/src/app.module.ts
  backend/src/auth/auth.controller.ts
  backend/src/infra/cookie/cookie.config.ts
  backend/src/infra/infra.config.ts
  backend/src/infra/infra.module.ts
  backend/src/infra/infra.service.ts
  backend/src/infra/redis/redis-client.ts
  backend/src/infra/typeorm/typeorm.config.ts
  backend/src/infra/websocket/websocket.entity.ts
  backend/src/infra/websocket/websocket.repository.ts
  backend/src/room/domain/room.ts
  backend/src/room/dto/all-room.dto.ts
  backend/src/room/dto/create-room.dto.ts
  backend/src/room/dto/index.ts
  backend/src/room/dto/join-room.dto.ts
  backend/src/room/dto/room-list.dto.ts
  backend/src/room/dto/room.dto.ts
  backend/src/room/exceptions/join-room-exceptions.ts
  backend/src/room/room.controller.ts
  backend/src/room/room.entity.ts
  backend/src/room/room.gateway.ts
  backend/src/room/room.module.ts
  backend/src/room/room.repository.ts
  backend/src/room/room.service.ts
  backend/src/room/services/room-create.service.ts
  backend/src/room/services/room-host.service.ts
  backend/src/room/services/room-join.service.ts
  backend/src/room/services/room-leave.service.ts
  backend/src/room/services/room.service.ts
  backend/src/signaling-server/sig-server.gateway.ts
  backend/src/websocket/websocket.config.ts
  backend/src/websocket/websocket.gateway.ts
  backend/src/websocket/websocket.module.ts
  backend/src/websocket/websocket.service.ts
Labels: 🎁 Refactoring

#320 [Refactor] 스터디 세션 부분 리팩토링 커밋
  backend/src/app.module.ts
  backend/src/auth/auth.controller.ts
  backend/src/infra/cookie/cookie.config.ts
  backend/src/infra/infra.config.ts
  backend/src/infra/infra.module.ts
  backend/src/infra/infra.service.ts
  backend/src/infra/redis/redis-client.ts
  backend/src/infra/typeorm/typeorm.config.ts
  backend/src/infra/websocket/websocket.entity.ts
  backend/src/infra/websocket/websocket.repository.ts
  backend/src/room/domain/room.ts
  backend/src/room/dto/all-room.dto.ts
  backend/src/room/dto/create-room.dto.ts
  backend/src/room/dto/index.ts
  backend/src/room/dto/join-room.dto.ts
  backend/src/room/dto/room-list.dto.ts
  backend/src/room/dto/room.dto.ts
  backend/src/room/exceptions/join-room-exceptions.ts
  backend/src/room/room.controller.ts
  backend/src/room/room.entity.ts
  backend/src/room/room.gateway.ts
  backend/src/room/room.module.ts
  backend/src/room/room.repository.ts
  backend/src/room/room.service.ts
  backend/src/room/services/room-create.service.ts
  backend/src/room/services/room-host.service.ts
  backend/src/room/services/room-join.service.ts
  backend/src/room/services/room-leave.service.ts
  backend/src/room/services/room.service.ts
  backend/src/signaling-server/sig-server.gateway.ts
  backend/src/websocket/websocket.config.ts
  backend/src/websocket/websocket.gateway.ts
  backend/src/websocket/websocket.module.ts
  backend/src/websocket/websocket.service.ts
Labels: 🎁 Refactoring

#321 [Refactor] 로그인 유무에 따른 에러 처리와 응답 반환
  backend/src/question-list/dto/get-all-question-list.dto.ts
  backend/src/question-list/dto/question-list-contents.dto.ts
  backend/src/question-list/question-list.controller.ts
  backend/src/question-list/question-list.service.ts
  backend/src/question-list/repository/question-list.repository.ts
Labels: 🐛 Bug Fix, 🎁 Refactoring

#322 [Fix] 비디오 오버레이 안보이던 문제 해결
  frontend/src/components/session/VideoProfileOverlay.tsx
Labels: 🐛 Bug Fix

#324 [Feat] 스크랩 기능 구현
  README.md
  frontend/src/components/common/Button/DefaultButton.tsx
  frontend/src/components/questions/detail/ButtonSection.tsx/index.tsx
  frontend/src/components/questions/detail/QuestionTitle.tsx/index.tsx
  frontend/src/hooks/api/useGetQuestionContent.ts
  frontend/src/pages/QuestionDetailPage/QuestionDetailPage.tsx
  frontend/src/pages/QuestionDetailPage/api/scrapAPI.ts
Labels: ✨ Feature

#325 [Fix] 소켓 연결 요청 3번 오류 수정
  backend/src/room/room.service.ts
  backend/src/room/services/room.service.ts
  frontend/src/hooks/useSocket.ts
  frontend/src/stores/useSocketStore.ts
Labels: 🐛 Bug Fix

#328 [Deploy] 6주차 4차 배포
  backend/src/room/room.gateway.ts
  backend/src/room/room.service.ts
  backend/src/room/services/room.service.ts
  frontend/src/api/question-list/getMyQuestionList.ts
  frontend/src/api/question-list/getScrapQuestionList.ts
  frontend/src/components/common/Button/DefaultButton.tsx
  frontend/src/components/mypage/QuestionList/index.tsx
  frontend/src/components/questions/detail/ButtonSection.tsx/index.tsx
  frontend/src/components/questions/detail/QuestionTitle.tsx/index.tsx
  frontend/src/components/session/CommonTools.tsx
  frontend/src/components/sessions/create/SessionForm/ListSelectModal/QuestionList/QuestionItem.tsx
  frontend/src/components/sessions/create/SessionForm/ListSelectModal/QuestionList/index.tsx
  frontend/src/components/sessions/create/SessionForm/ListSelectModal/index.tsx
  frontend/src/hooks/api/useGetMyQuestionList.ts
  frontend/src/hooks/api/useGetQuestionContent.ts
  frontend/src/hooks/useSocket.ts
  frontend/src/pages/QuestionDetailPage/QuestionDetailPage.tsx
  frontend/src/pages/QuestionDetailPage/api/scrapAPI.ts
  frontend/src/pages/QuestionListPage/view/QuestionListHeader.tsx
  frontend/src/pages/QuestionListPage/view/Tabs.tsx
  frontend/src/pages/SessionListPage/SessionListPage.tsx
  frontend/src/pages/SessionListPage/view/Tab.tsx
  frontend/src/pages/SessionListPage/view/TabContainer.tsx
  frontend/src/pages/SessionPage/hooks/useBlockNavigate.ts
  frontend/src/pages/SessionPage/hooks/useSession.ts
  frontend/src/stores/useSocketStore.ts
  frontend/vite.config.ts
Labels: 📣 Deploy

#329 [Fix] 빌드에러 수정, vendor 파일로 리액트 라이브러리 별도의 청크 파일 분리
  frontend/vite.config.ts
Labels: 🐛 Bug Fix

#330 [Refactor] 다크모드 비활성화 ㅠㅠ
  frontend/src/components/common/Sidebar/Sidebar.tsx
  frontend/vite.config.ts
Labels: 🎁 Refactoring

#332 [Deploy] 6주차 5차 배포
  backend/src/room/exceptions/join-room-exceptions.ts
  backend/src/room/room.events.ts
  backend/src/room/room.gateway.ts
  backend/src/room/room.service.ts
  frontend/src/components/common/Animate/NotFound.tsx
  frontend/src/components/common/Sidebar/Sidebar.tsx
  frontend/src/components/session/CommonTools.tsx
  frontend/src/components/session/MediaPreviewModal.tsx
  frontend/src/components/session/VideoContainer.tsx
  frontend/src/constants/WebSocket/SessionEvent.ts
  frontend/src/hooks/useSocket.ts
  frontend/src/pages/SessionListPage/view/SessionList.tsx
  frontend/src/pages/SessionPage/SessionPage.tsx
  frontend/src/pages/SessionPage/hooks/useBlockNavigate.ts
  frontend/src/pages/SessionPage/hooks/useMediaDevices.ts
  frontend/src/pages/SessionPage/hooks/useSession.ts
  frontend/src/pages/SessionPage/hooks/useSocketEvents.ts
  frontend/src/pages/SessionPage/view/SessionToolbar.tsx
  frontend/src/routes.tsx
Labels: 📣 Deploy

#333 [Refactor] k6로 queryRunner 적용한 트랜잭션 성능 테스트하기
  backend/package.json
  backend/src/question-list/question-list.service.ts
  backend/src/question-list/repository/question.respository.ts
  backend/test/k6/create-question-list-test.ts
  backend/test/k6/delete-question-test.ts
Labels: 🎁 Refactoring

#334 [Design] 사이드바 로고 제작 및 일부 스타일 통일
  frontend/public/preview-logo2.png
  frontend/src/components/common/Sidebar/Sidebar.tsx
  frontend/src/components/common/Sidebar/SidebarMenu.tsx
  frontend/src/components/questions/QuestionsPreviewCard.tsx
  frontend/src/pages/QuestionListPage/view/QuestionListHeader.tsx
  frontend/src/pages/QuestionListPage/view/Tabs.tsx
  frontend/src/pages/SessionListPage/SessionListPage.tsx
  frontend/src/pages/SessionListPage/view/SessionCard.tsx
  frontend/src/pages/SessionListPage/view/Tab.tsx
  frontend/src/pages/SessionListPage/view/TabContainer.tsx
  frontend/tailwind.config.js
Labels: 🎨 Design

#335 [Fix] 비디오 끄고 참가시 안보이던 문제 해결
  frontend/src/components/session/MediaPreviewModal.tsx
  frontend/src/pages/SessionPage/hooks/useBlockNavigate.ts
  frontend/src/pages/SessionPage/hooks/useMediaDevices.ts
  frontend/src/pages/SessionPage/hooks/usePeerConnection.ts
  frontend/src/pages/SessionPage/hooks/useSession.ts
Labels: 🐛 Bug Fix

#336 [Deploy] 6주차 6차 배포
  backend/package.json
  backend/src/question-list/question-list.service.ts
  backend/src/question-list/repository/question.respository.ts
  backend/test/k6/create-question-list-test.ts
  backend/test/k6/delete-question-test.ts
  frontend/public/preview-logo2.png
  frontend/src/components/common/Sidebar/Sidebar.tsx
  frontend/src/components/common/Sidebar/SidebarMenu.tsx
  frontend/src/components/questions/QuestionsPreviewCard.tsx
  frontend/src/components/session/MediaPreviewModal.tsx
  frontend/src/pages/QuestionListPage/view/QuestionListHeader.tsx
  frontend/src/pages/QuestionListPage/view/Tabs.tsx
  frontend/src/pages/SessionListPage/SessionListPage.tsx
  frontend/src/pages/SessionListPage/view/SessionCard.tsx
  frontend/src/pages/SessionListPage/view/Tab.tsx
  frontend/src/pages/SessionListPage/view/TabContainer.tsx
  frontend/src/pages/SessionPage/hooks/useBlockNavigate.ts
  frontend/src/pages/SessionPage/hooks/useMediaDevices.ts
  frontend/src/pages/SessionPage/hooks/usePeerConnection.ts
  frontend/src/pages/SessionPage/hooks/useSession.ts
  frontend/tailwind.config.js
Labels: 📣 Deploy
