Repository boostcampwm-2024/web27-Preview, pull requests merged in 2024-11, with the labels that each got.

#53 [기능 추가] 협업을 위한 라우터 설정
  frontend/src/routes.tsx
Labels: ✨ Feature

#52 [기능 추가] 프론트엔드 협업을 위한 react-router 설치 및 간단한 비디오 켜기 기능 구현
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/main.tsx
  frontend/src/routes.tsx
  pnpm-lock.yaml
Labels: ✨ Feature

#54 Signaling server 구현
  backend/package.json
  backend/src/app.controller.spec.ts
  backend/src/app.controller.ts
  backend/src/app.module.ts
  backend/src/app.service.ts
  backend/src/main.ts
  backend/src/socket/socket.gateway.ts
  backend/src/socket/socket.module.ts
Labels: ✨ Feature

#55 [기능 추가] 스터디 세션 리스트 페이지 구현
  frontend/.gitignore
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/components/SessionCard.tsx
  frontend/src/index.css
  frontend/src/main.tsx
  frontend/src/pages/SessionListPage.tsx
  frontend/src/routes.tsx
  frontend/tailwind.config.js
  pnpm-lock.yaml
Labels: ✨ Feature

#56 [Feat] WebRTC 통신 및 비디오 컴포넌트 구현
  backend/package.json
  backend/src/app.controller.spec.ts
  backend/src/app.controller.ts
  backend/src/app.module.ts
  backend/src/app.service.ts
  backend/src/main.ts
  backend/src/socket/socket.gateway.ts
  backend/src/socket/socket.module.ts
  commitlint.config.js
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/assets/mike-off.svg
  frontend/src/assets/mike-on.svg
  frontend/src/assets/video_profile.svg
  frontend/src/components/VideoContainer.tsx
  frontend/src/components/VideoRoom.tsx
  frontend/src/main.tsx
  frontend/src/pages/SessionListPage.tsx
  frontend/src/pages/SessionPage.tsx
  frontend/src/routes.tsx
  pnpm-lock.yaml
Labels: ✨ Feature

#58 [Feat] 미디어 장치 선택기능, 화상회의 세션 내부 UI 및 vite 콘솔로그 제거 플러그인 설치
  frontend/package.json
  frontend/src/components/VideoContainer.tsx
  frontend/src/components/VideoRoom.tsx
  frontend/src/pages/SessionPage.tsx
  frontend/vite.config.ts
  pnpm-lock.yaml
Labels: ✨ Feature

#60 [Design] 세션 리스트 페이지 디자인
  frontend/src/components/SessionCard.tsx
  frontend/src/index.css
  frontend/src/pages/SessionListPage.tsx
  frontend/tailwind.config.js
Labels: 🎨 Design

#65 [Feat] 배포 워크플로우 추가
  .github/workflows/deploy.yml
Labels: ✨ Feature

#67 [Docs] Preview 배너 이미지 추가
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
Labels: 📄 Documents

#63 [Refactor] 세션 페이지 컴포넌트 분리, 커스텀 훅 분리, UI 개선, 화상 회의 도중 미디어 장치 변경 가능하도록 수정
  frontend/src/App.css
  frontend/src/assets/fonts/PretendardVariable.woff2
  frontend/src/components/session/SessionSidebar.tsx
  frontend/src/components/session/SessionToolbar.tsx
  frontend/src/components/session/VideoContainer.tsx
  frontend/src/hooks/useMediaDevices.ts
  frontend/src/hooks/useSocket.ts
  frontend/src/index.css
  frontend/src/pages/SessionPage.tsx
Labels: 🎁 Refactoring

#108 [Feat] 공감 기능 구현, 렌더링 최적화와 깜빡임 이슈 해결
  backend/src/socket/socket.gateway.ts
  frontend/src/components/session/DisplayMediaStream.tsx
  frontend/src/components/session/SessionToolbar.tsx
  frontend/src/components/session/VideoContainer.tsx
  frontend/src/pages/SessionPage.tsx
Labels: ✨ Feature, 화상통화 기능

#110 [Feat] 토스트 메시지 커스터 훅 구현 및 전역적인 토스트 메시지 관리 스토어 구현
  frontend/package.json
  frontend/src/components/common/ProgressBar.tsx
  frontend/src/components/common/Toast.tsx
  frontend/src/components/common/ToastProvider.tsx
  frontend/src/hooks/useToast.ts
  frontend/src/index.css
  frontend/src/main.tsx
  frontend/src/pages/SessionListPage.tsx
  frontend/src/stores/useToastStore.ts
  pnpm-lock.yaml
Labels: ✨ Feature

#114 Feature/study session
  backend/package.json
  backend/src/app.module.ts
  backend/src/config/redis.config.ts
  backend/src/redis/redis.module.ts
  backend/src/redis/redis.service.spec.ts
  backend/src/redis/redis.service.ts
  backend/src/room/room.gateway.spec.ts
  backend/src/room/room.gateway.ts
  backend/src/room/room.model.ts
  backend/src/room/room.module.ts
  backend/src/room/room.service.spec.ts
  backend/src/room/room.service.ts
  backend/src/signaling-server/socket.gateway.ts
  backend/src/signaling-server/socket.module.ts
  backend/src/socket/socket.gateway.ts
  backend/src/utils/generateRoomId.ts
  backend/src/utils/time.ts
  pnpm-lock.yaml
Labels: ✨ Feature, 스터디 세션 기능

#113 [Feat] 세션 만들기 페이지 구현
  frontend/src/assets/fonts/PretendardVariable.woff2
  frontend/src/assets/mike-off.svg
  frontend/src/assets/mike-on.svg
  frontend/src/assets/react.svg
  frontend/src/assets/video_profile.svg
  frontend/src/components/sessions/SessionCard.tsx
  frontend/src/components/sessions/create/SelectTitle.tsx
  frontend/src/components/sessions/create/SessionForm/AccessSection/index.tsx
  frontend/src/components/sessions/create/SessionForm/CategorySection/index.tsx
  frontend/src/components/sessions/create/SessionForm/ListSelectModal/CategoryTab.tsx
  frontend/src/components/sessions/create/SessionForm/ListSelectModal/data.ts
  frontend/src/components/sessions/create/SessionForm/ListSelectModal/index.tsx
  frontend/src/components/sessions/create/SessionForm/NameSection/index.tsx
  frontend/src/components/sessions/create/SessionForm/ParticipantSection/ParticpantButton.tsx
  frontend/src/components/sessions/create/SessionForm/ParticipantSection/index.tsx
  frontend/src/components/sessions/create/SessionForm/QuestionListSection/index.tsx
  frontend/src/components/sessions/create/SessionForm/index.tsx
  frontend/src/components/utils/SearchBar.tsx
  frontend/src/pages/CreateSessionPage.tsx
  frontend/src/pages/SessionListPage.tsx
  frontend/src/routes.tsx
  frontend/tailwind.config.js
Labels: ✨ Feature

#116 [Fix] 카메라를 꺼도 인디케이터가 켜져있던 문제 해결
  frontend/src/hooks/useMediaDevices.ts
  frontend/src/hooks/usePeerConnection.ts
  frontend/src/hooks/useSocket.ts
  frontend/src/pages/SessionPage.tsx
Labels: 🐛 Bug Fix

#115 [Feat] 공통 모달창 구현
  frontend/src/components/common/Modal/Title.tsx
  frontend/src/components/common/Modal/index.tsx
  frontend/src/components/common/SearchBar.tsx
  frontend/src/components/sessions/create/SessionForm/AccessSection/index.tsx
  frontend/src/components/sessions/create/SessionForm/ListSelectModal/index.tsx
  frontend/src/components/sessions/create/SessionForm/ParticipantSection/index.tsx
  frontend/src/components/sessions/create/SessionForm/QuestionListSection/index.tsx
  frontend/src/components/sessions/create/SessionForm/index.tsx
  frontend/src/hooks/useModal.ts
  frontend/src/pages/SessionListPage.tsx
  frontend/src/stores/useModalStore.ts
  frontend/src/stores/useSessionFormStore.ts
  frontend/tailwind.config.js
Labels: ✨ Feature

#117 [Feat] 방 만들기 구현 (서버 연결 빼고)
  frontend/package.json
  frontend/src/components/common/Modal/index.tsx
  frontend/src/components/session/SessionSidebar.tsx
  frontend/src/components/sessions/create/SessionForm/AccessSection/index.tsx
  frontend/src/components/sessions/create/SessionForm/CategorySection/index.tsx
  frontend/src/components/sessions/create/SessionForm/ListSelectModal/CategoryTab.tsx
  frontend/src/components/sessions/create/SessionForm/ListSelectModal/CategoryTab/Category.tsx
  frontend/src/components/sessions/create/SessionForm/ListSelectModal/CategoryTab/index.tsx
  frontend/src/components/sessions/create/SessionForm/ListSelectModal/QuestionList/QuestionItem.tsx
  frontend/src/components/sessions/create/SessionForm/ListSelectModal/QuestionList/index.tsx
  frontend/src/components/sessions/create/SessionForm/ListSelectModal/index.tsx
  frontend/src/components/sessions/create/SessionForm/NameSection/index.tsx
  frontend/src/components/sessions/create/SessionForm/ParticipantSection/ParticpantButton.tsx
  frontend/src/components/sessions/create/SessionForm/ParticipantSection/index.tsx
  frontend/src/components/sessions/create/SessionForm/QuestionListSection/index.tsx
  frontend/src/components/sessions/create/SessionForm/index.tsx
  frontend/src/hooks/useSocket.ts
  frontend/src/pages/CreateSessionPage.tsx
  frontend/src/pages/SessionListPage.tsx
  frontend/src/pages/SessionPage.tsx
  frontend/src/stores/useSessionFormStore.ts
  frontend/src/stores/useSocketStore.ts
  frontend/tsconfig.app.json
  frontend/tsconfig.json
  frontend/vite.config.ts
  pnpm-lock.yaml
Labels: ✨ Feature

#120 [Feat] 세션 만들기 후 방 입장 | 링크 공유해서 들어올 수 있게 설정
  frontend/src/components/session/SessionSidebar.tsx
  frontend/src/components/sessions/create/SessionForm/AccessSection/index.tsx
  frontend/src/components/sessions/create/SessionForm/ListSelectModal/QuestionList/QuestionItem.tsx
  frontend/src/components/sessions/create/SessionForm/ParticipantSection/ParticpantButton.tsx
  frontend/src/components/sessions/create/SessionForm/index.tsx
  frontend/src/pages/SessionPage.tsx
  frontend/vite.config.ts
Labels: ✨ Feature

#119 [Feat] 스터디 세션 기능 서버측 기능 추가
  backend/package.json
  backend/src/app.module.ts
  backend/src/config/redis.config.ts
  backend/src/redis/redis.module.ts
  backend/src/redis/redis.service.spec.ts
  backend/src/redis/redis.service.ts
  backend/src/room/dto/create-room.dto.ts
  backend/src/room/room.controller.spec.ts
  backend/src/room/room.controller.ts
  backend/src/room/room.gateway.spec.ts
  backend/src/room/room.gateway.ts
  backend/src/room/room.model.ts
  backend/src/room/room.module.ts
  backend/src/room/room.repository.ts
  backend/src/room/room.service.spec.ts
  backend/src/room/room.service.ts
  backend/src/signaling-server/socket.gateway.ts
  backend/src/signaling-server/socket.module.ts
  backend/src/utils/generateRoomId.ts
  backend/src/utils/time.ts
  pnpm-lock.yaml
Labels: ✨ Feature, 스터디 세션 기능

#121 [Feat] 세션 입장 로직 구현 및 세션 내부 이벤트에 대한 대응 구현
  backend/package.json
  backend/src/app.module.ts
  backend/src/config/redis.config.ts
  backend/src/redis/redis.module.ts
  backend/src/redis/redis.service.spec.ts
  backend/src/redis/redis.service.ts
  backend/src/room/dto/create-room.dto.ts
  backend/src/room/room.controller.spec.ts
  backend/src/room/room.controller.ts
  backend/src/room/room.gateway.spec.ts
  backend/src/room/room.gateway.ts
  backend/src/room/room.model.ts
  backend/src/room/room.module.ts
  backend/src/room/room.repository.ts
  backend/src/room/room.service.spec.ts
  backend/src/room/room.service.ts
  backend/src/signaling-server/socket.gateway.ts
  backend/src/signaling-server/socket.module.ts
  backend/src/utils/generateRoomId.ts
  backend/src/utils/time.ts
  frontend/src/components/session/SessionHeader.tsx
  frontend/src/components/session/SessionSidebar.tsx
  frontend/src/components/sessions/create/SessionForm/AccessSection/index.tsx
  frontend/src/components/sessions/create/SessionForm/index.tsx
  frontend/src/hooks/usePeerConnection.ts
  frontend/src/hooks/useSocket.ts
  frontend/src/pages/SessionPage.tsx
  frontend/src/stores/useSessionFormStore.ts
  frontend/src/stores/useSocketStore.ts
  pnpm-lock.yaml
Labels: ✨ Feature

#124 [Feat] 404 에러 페이지 구현
  frontend/package.json
  frontend/public/assets/snowman.json
  frontend/src/pages/ErrorPage.tsx
  frontend/src/routes.tsx
  pnpm-lock.yaml
Labels: ✨ Feature

#126 [Feat] 사이드바 공용 컴포넌트 구현
  frontend/src/components/common/Sidebar.tsx
  frontend/src/pages/SessionListPage.tsx
Labels: ✨ Feature

#136 [Feat] 다크모드 커스텀 훅 구현 및 다크모드 토글 버튼 추가
  frontend/src/components/common/Sidebar.tsx
  frontend/src/hooks/useTheme.ts
  frontend/src/index.css
  frontend/tailwind.config.js
Labels: ✨ Feature

#135 [Test] useSession 테스트 코드 작성
  frontend/jest.config.ts
  frontend/package.json
  frontend/src/hooks/__test__/mocks/useSession.mock.ts
  frontend/src/hooks/__test__/useSession.test.ts
  frontend/src/hooks/type/session.d.ts
  frontend/src/hooks/type/session.test.d.ts
  frontend/src/hooks/useSession.ts
  frontend/src/hooks/useSocket.ts
  frontend/src/hooks/useToast.ts
  frontend/src/pages/SessionPage.tsx
  frontend/src/setupTests.ts
  frontend/tsconfig.json
  frontend/tsconfig.test.json
  pnpm-lock.yaml
Labels: ⚙️ Test

#151 [Feat] GitHub OAuth 기능 구현 및 유저 Entity 및 Repository 구현
  backend/package.json
  backend/src/app.module.ts
  backend/src/auth/auth.controller.spec.ts
  backend/src/auth/auth.controller.ts
  backend/src/auth/auth.module.ts
  backend/src/auth/auth.service.spec.ts
  backend/src/auth/auth.service.ts
  backend/src/auth/strategy/github.strategy.ts
  backend/src/main.ts
  backend/src/user/dto/create-user.dto.ts
  backend/src/user/user.entity.ts
  backend/src/user/user.module.ts
  backend/src/user/user.repository.ts
  frontend/package.json
  frontend/public/assets/snowman.json
  frontend/src/pages/ErrorPage.tsx
  frontend/src/routes.tsx
  pnpm-lock.yaml
Labels: ✨ Feature, 로그인 회원가입 기능

#152 [Feat] 면접 질문지 리스트 페이지 구현, 공통 컴포넌트 분리
  frontend/public/assets/loadingIndicator.lottie
  frontend/src/components/common/LoadingIndicator.tsx
  frontend/src/components/common/SearchBar.tsx
  frontend/src/components/common/Select.tsx
  frontend/src/components/common/Sidebar.tsx
  frontend/src/components/questions/QuestionsPreviewCard.tsx
  frontend/src/index.css
  frontend/src/pages/QuestionListPage.tsx
  frontend/src/pages/SessionListPage.tsx
  frontend/src/routes.tsx
Labels: ✨ Feature

#173 [Refactor] Toast 메시지 리팩토링
  frontend/src/components/common/Toast.tsx
  frontend/src/components/common/ToastProvider.tsx
  frontend/src/hooks/useToast.ts
  frontend/src/stores/useToastStore.ts
  pnpm-lock.yaml
Labels: 🎁 Refactoring

#174 [Feat] OAuth + JWT 구현
  backend/package.json
  backend/src/app.module.ts
  backend/src/auth/auth.controller.ts
  backend/src/auth/auth.module.ts
  backend/src/auth/auth.service.ts
  backend/src/auth/jwt.guard.ts
  backend/src/auth/strategy/github.strategy.ts
  backend/src/auth/strategy/jwt.strategy.ts
  backend/src/config/typeorm.config.ts
  backend/src/question-list/dto/create-question-list.dto.ts
  backend/src/question-list/dto/create-question.dto.ts
  backend/src/question-list/dto/question.dto.ts
  backend/src/question-list/question-list.controller.spec.ts
  backend/src/question-list/question-list.controller.ts
  backend/src/question-list/question-list.entity.ts
  backend/src/question-list/question-list.module.ts
  backend/src/question-list/question-list.repository.ts
  backend/src/question-list/question-list.service.spec.ts
  backend/src/question-list/question-list.service.ts
  backend/src/question-list/question.entity.ts
  backend/src/user/dto/user.dto.ts
  backend/src/user/user.entity.ts
  backend/src/user/user.module.ts
  backend/src/user/user.repository.ts
Labels: ✨ Feature

#177 [Design] 일부 페이지 디자인 통일
  frontend/package.json
  frontend/src/components/common/SearchBar.tsx
  frontend/src/components/common/Select.tsx
  frontend/src/components/common/Sidebar.tsx
  frontend/src/components/questions/QuestionsPreviewCard.tsx
  frontend/src/components/sessions/SessionCard.tsx
  frontend/src/main.tsx
  frontend/src/pages/ErrorPage.tsx
  frontend/src/pages/LoginPage.tsx
  frontend/src/pages/QuestionListPage.tsx
  frontend/src/pages/SessionListPage.tsx
  frontend/tailwind.config.js
Labels: 🎨 Design

#179 [Feat] 세션 리스트 렌더링 함수 구현 및 세션 데이터 구조 변경
  frontend/src/components/sessions/SessionCard.tsx
  frontend/src/pages/SessionListPage.tsx
Labels: ✨ Feature

#178 [Feat] JWT 토큰 기반 인증 기능 추가
  backend/package.json
  backend/src/auth/auth.controller.ts
  backend/src/auth/auth.module.ts
  backend/src/auth/auth.service.ts
  backend/src/auth/github/github.strategy.ts
  backend/src/auth/github/gitub-profile.decorator.ts
  backend/src/auth/jwt.guard.ts
  backend/src/auth/jwt/jwt.decorator.ts
  backend/src/auth/jwt/jwt.model.ts
  backend/src/auth/jwt/jwt.module.ts
  backend/src/auth/jwt/jwt.service.ts
  backend/src/auth/jwt/strategy/access-token.strategy.ts
  backend/src/auth/jwt/strategy/refresh-token.strategy.ts
  backend/src/auth/strategy/github.strategy.ts
  backend/src/auth/strategy/jwt.strategy.ts
  backend/src/config/cookie.config.ts
  backend/src/main.ts
  backend/src/utils/time.ts
  frontend/index.html
  frontend/jest.config.ts
  frontend/package.json
  frontend/public/assets/loadingIndicator.lottie
  frontend/public/assets/noondeumyum.lottie
  frontend/src/components/common/LoadingIndicator.tsx
  frontend/src/components/common/SearchBar.tsx
  frontend/src/components/common/Select.tsx
  frontend/src/components/common/Sidebar.tsx
  frontend/src/components/questions/QuestionsPreviewCard.tsx
  frontend/src/hooks/__test__/mocks/useSession.mock.ts
  frontend/src/hooks/__test__/useSession.test.ts
  frontend/src/hooks/type/session.d.ts
  frontend/src/hooks/type/session.test.d.ts
  frontend/src/hooks/useSession.ts
  frontend/src/hooks/useSocket.ts
  frontend/src/hooks/useTheme.ts
  frontend/src/hooks/useToast.ts
  frontend/src/index.css
  frontend/src/main.tsx
  frontend/src/pages/Login/AuthCallbackPage.tsx
  frontend/src/pages/LoginPage.tsx
  frontend/src/pages/QuestionListPage.tsx
  frontend/src/pages/SessionListPage.tsx
  frontend/src/pages/SessionPage.tsx
  frontend/src/routes.tsx
  frontend/src/setupTests.ts
  frontend/src/types/declarations.d.ts
  frontend/tailwind.config.js
  frontend/tsconfig.app.json
  frontend/tsconfig.json
  frontend/tsconfig.test.json
  frontend/vite.config.ts
  pnpm-lock.yaml
Labels: ✨ Feature, 로그인 회원가입 기능

#172 [Test] 백엔드 테스트 코드 추가
  backend/src/auth/auth.service.spec.ts
  backend/src/redis/redis.service.spec.ts
  backend/src/room/room.controller.spec.ts
  backend/src/room/room.gateway.spec.ts
  backend/src/room/room.repository.ts
  backend/src/room/room.service.spec.ts
Labels: ⚙️ Test

#189 [Refactor] 세션 생성 페이지 사이드바 추가 및 로딩 추가
  frontend/src/constraints/LayoutConstant.ts
  frontend/src/hooks/useToast.ts
  frontend/src/pages/CreateSessionPage.tsx
  frontend/src/pages/SessionListPage.tsx
  pnpm-lock.yaml
Labels: 🎁 Refactoring

#191 [Refactor] 로티 애니메이션 관련 오류 해결 및 최적화
  frontend/public/assets/snowman.json
  frontend/public/assets/snowman.lottie
  frontend/src/pages/ErrorPage.tsx
  frontend/src/pages/LoginPage.tsx
Labels: 🎁 Refactoring

#190 [Chore] docker compose 기능 추가
  .gitignore
  docker-compose.yml
Labels: ✨ Feature

#194 [Feat] 질문지 상세보기 페이지 구현
  frontend/src/api/questions/create.ts
  frontend/src/api/questions/getQuestion.ts
  frontend/src/components/common/Sidebar.tsx
  frontend/src/components/common/TitleInput/index.tsx
  frontend/src/components/questions/create/QuestionForm/QuestionInputSection/QuestionInput.tsx
  frontend/src/components/questions/create/QuestionForm/index.tsx
  frontend/src/components/questions/detail/ButtonSection.tsx/Button.tsx
  frontend/src/components/questions/detail/ButtonSection.tsx/index.tsx
  frontend/src/components/questions/detail/QuestionList.tsx/QuestionItem.tsx
  frontend/src/components/questions/detail/QuestionList.tsx/index.tsx
  frontend/src/components/questions/detail/QuestionTitle.tsx/index.tsx
  frontend/src/components/sessions/create/SessionForm/ListSelectModal/Pagination/index.tsx
  frontend/src/components/sessions/create/SessionForm/ListSelectModal/QuestionList/QuestionItem.tsx
  frontend/src/components/sessions/create/SessionForm/ListSelectModal/QuestionList/index.tsx
  frontend/src/components/sessions/create/SessionForm/ListSelectModal/constant.ts
  frontend/src/components/sessions/create/SessionForm/ListSelectModal/data.ts
  frontend/src/components/sessions/create/SessionForm/ListSelectModal/index.tsx
  frontend/src/hooks/useCreateQuestion.ts
  frontend/src/hooks/useGetQuestion.ts
  frontend/src/pages/QuestionDetailPage.tsx
  frontend/src/routes.tsx
  pnpm-lock.yaml
Labels: ✨ Feature

#195 [Fix] 열려있는 세션이 없을 경우에 대한 예외처리, 세션 리스트 GET API 수정
  backend/src/room/room.repository.ts
  backend/src/room/room.service.ts
Labels: 🐛 Bug Fix, 스터디 세션 기능

#196 [Feat] 스터디룸 생성에 질문 내용 전달, 질문지 기능 버그 fix
  backend/src/question-list/dto/create-question-list.dto.ts
  backend/src/question-list/dto/question-list.dto.ts
  backend/src/question-list/dto/question.dto.ts
  backend/src/question-list/question-list.controller.ts
  backend/src/question-list/question-list.module.ts
  backend/src/question-list/question-list.repository.ts
  backend/src/question-list/question-list.service.ts
  backend/src/question-list/question.entity.ts
  backend/src/room/dto/create-room.dto.ts
  backend/src/room/room.gateway.ts
  backend/src/room/room.model.ts
  backend/src/room/room.module.ts
  backend/src/room/room.repository.ts
  backend/src/room/room.service.spec.ts
  backend/src/room/room.service.ts
Labels: 🐛 Bug Fix, 스터디 세션 기능, 질문지 기능

#193 [Feat] 로그인 전역상태 관리 및 커스텀 훅 구현, 질문지 생성 로그인한 유저만 가능하도록 제한, 마이페이지 라우팅
  frontend/src/components/common/Sidebar.tsx
  frontend/src/hooks/useAuth.ts
  frontend/src/pages/CreateQuestionPage.tsx
  frontend/src/pages/Login/AuthCallbackPage.tsx
  frontend/src/pages/Login/LoginPage.tsx
  frontend/src/pages/MyPage.tsx
  frontend/src/pages/QuestionListPage.tsx
  frontend/src/routes.tsx
  frontend/src/stores/useAuthStore.ts
Labels: ✨ Feature

#197 [Feat] 질문지리스트 API 연동, 세션 생성시 질문지 선택 및 질문 목록 보기 기능 구현, 세션 생성시 질문지 ID 전달
  backend/src/question-list/dto/get-all-question-list.dto.ts
  backend/src/question-list/dto/my-question-list.dto.ts
  backend/src/question-list/dto/question-list-contents.dto.ts
  backend/src/question-list/question-list.controller.ts
  backend/src/question-list/question-list.entity.ts
  backend/src/question-list/question-list.repository.ts
  backend/src/question-list/question-list.service.ts
  frontend/src/components/questions/QuestionsPreviewCard.tsx
  frontend/src/components/sessions/create/SessionForm/ListSelectModal/QuestionList/QuestionItem.tsx
  frontend/src/components/sessions/create/SessionForm/ListSelectModal/QuestionList/index.tsx
  frontend/src/components/sessions/create/SessionForm/ListSelectModal/index.tsx
  frontend/src/components/sessions/create/SessionForm/index.tsx
  frontend/src/pages/QuestionListPage.tsx
  frontend/src/vite-env.d.ts
  frontend/tsconfig.app.json
  frontend/vite.config.ts
Labels: ✨ Feature

#206 [Feat] 페이지 메타데이터 수정 및 오픈그래프, 파비콘 추가 등
  frontend/index.html
  frontend/public/preview-logo.svg
Labels: ✨ Feature

#205 [Refactor] 스터디 세션 기능 리워크
  .prettierrc
  backend/package.json
  backend/src/app.controller.spec.ts
  backend/src/app.module.ts
  backend/src/question-list/question-list.repository.ts
  backend/src/redis/redis.module.ts
  backend/src/redis/redis.service.spec.ts
  backend/src/redis/redis.service.ts
  backend/src/room/dto/create-room.dto.ts
  backend/src/room/dto/join-room.dto.ts
  backend/src/room/dto/reaction.dto.ts
  backend/src/room/dto/room.dto.ts
  backend/src/room/room.controller.spec.ts
  backend/src/room/room.controller.ts
  backend/src/room/room.entity.ts
  backend/src/room/room.gateway.spec.ts
  backend/src/room/room.gateway.ts
  backend/src/room/room.model.ts
  backend/src/room/room.module.ts
  backend/src/room/room.repository.ts
  backend/src/room/room.service.spec.ts
  backend/src/room/room.service.ts
  backend/src/room/services/room-host.service.ts
  backend/src/room/services/room-leave.service.ts
  backend/src/room/services/room.service.ts
  backend/src/room/socket/room-socket.entity.ts
  backend/src/room/socket/room-socket.events.ts
  backend/src/room/socket/room-socket.gateway.ts
  backend/src/room/socket/room-socket.repository.ts
  backend/src/room/socket/room-socket.service.ts
  backend/src/signaling-server/sig-server.event.ts
  backend/src/signaling-server/sig-server.gateway.ts
  backend/src/signaling-server/sig-server.module.ts
  backend/src/signaling-server/socket.module.ts
  backend/tsconfig.json
  pnpm-lock.yaml
Labels: 🎁 Refactoring

#207 [Refactor] useSession 리팩토링
  .gitignore
  backend/src/config/typeorm.config.ts
  backend/src/question-list/dto/create-question-list.dto.ts
  backend/src/question-list/dto/question-list.dto.ts
  backend/src/question-list/dto/question.dto.ts
  backend/src/question-list/question-list.controller.ts
  backend/src/question-list/question-list.module.ts
  backend/src/question-list/question-list.repository.ts
  backend/src/question-list/question-list.service.ts
  backend/src/question-list/question.entity.ts
  backend/src/room/dto/create-room.dto.ts
  backend/src/room/room.gateway.ts
  backend/src/room/room.model.ts
  backend/src/room/room.module.ts
  backend/src/room/room.repository.ts
  backend/src/room/room.service.spec.ts
  backend/src/room/room.service.ts
  docker-compose.yml
  frontend/src/api/questions/getQuestion.ts
  frontend/src/components/sessions/create/SessionForm/ListSelectModal/CategoryTab/Category.tsx
  frontend/src/components/sessions/create/SessionForm/ListSelectModal/QuestionList/QuestionItem.tsx
  frontend/src/components/sessions/create/SessionForm/ListSelectModal/QuestionList/index.tsx
  frontend/src/components/sessions/create/SessionForm/ListSelectModal/data.ts
  frontend/src/hooks/__test__/useSession.test.ts
  frontend/src/hooks/session/useMediaDevices.ts
  frontend/src/hooks/session/useMediaStreamCleanup.ts
  frontend/src/hooks/session/usePeerConnection.ts
  frontend/src/hooks/session/usePeerConnectionCleanup.ts
  frontend/src/hooks/session/useReaction.ts
  frontend/src/hooks/session/useSession.ts
  frontend/src/hooks/session/useSocketEvents.ts
  frontend/src/hooks/type/session.d.ts
  frontend/src/pages/QuestionListPage.tsx
  frontend/src/pages/SessionPage.tsx
  frontend/src/stores/useSocketStore.ts
  frontend/tsconfig.app.json
  frontend/tsconfig.test.json
Labels: 🎁 Refactoring

#223 [Fix] 미디어 장치 끄고 다시 켜지지 않던 문제 해결
  frontend/src/api/questions/getQuestion.ts
  frontend/src/components/sessions/create/SessionForm/ListSelectModal/CategoryTab/Category.tsx
  frontend/src/components/sessions/create/SessionForm/ListSelectModal/QuestionList/QuestionItem.tsx
  frontend/src/components/sessions/create/SessionForm/ListSelectModal/QuestionList/index.tsx
  frontend/src/components/sessions/create/SessionForm/ListSelectModal/data.ts
  frontend/src/hooks/__test__/useSession.test.ts
  frontend/src/hooks/session/useMediaDevices.ts
  frontend/src/hooks/session/useMediaStreamCleanup.ts
  frontend/src/hooks/session/usePeerConnection.ts
  frontend/src/hooks/session/usePeerConnectionCleanup.ts
  frontend/src/hooks/session/useReaction.ts
  frontend/src/hooks/session/useSession.ts
  frontend/src/hooks/session/useSocketEvents.ts
  frontend/src/hooks/type/session.d.ts
  frontend/src/pages/QuestionListPage.tsx
  frontend/src/pages/SessionPage.tsx
  frontend/src/stores/useSocketStore.ts
  frontend/tsconfig.app.json
  frontend/tsconfig.test.json
Labels: 🐛 Bug Fix

#225 [Fix] Select 컴포넌트 Props 오류 해결
  frontend/src/pages/SessionListPage.tsx
Labels: 🐛 Bug Fix

#226 [Refactor] index.html 메타데이터 og-image 확장자 변경 및 deprecated 태그 제거
  frontend/index.html
  frontend/public/snowman-thumbnail.jpg
Labels: 🎁 Refactoring

#229 [Fix] select 컴포넌트 관련 오류 해결
  frontend/src/pages/SessionListPage.tsx
Labels: 🐛 Bug Fix

#231 [Fix] category 필드 추가, 명세에 맞게 엔티티 DTO 수정
  backend/src/room/dto/create-room.dto.ts
  backend/src/room/dto/room.dto.ts
  backend/src/room/room.controller.ts
  backend/src/room/room.entity.ts
  backend/src/room/room.gateway.ts
  backend/src/room/room.repository.ts
  backend/src/room/services/room-create.service.ts
  backend/src/room/services/room-host.service.ts
  backend/src/room/services/room-join.service.ts
  backend/src/room/services/room-leave.service.ts
Labels: 🐛 Bug Fix, ✨ Feature

#250 [Refactor] 서버 세션 리팩토링 대응하기
  backend/src/room/dto/create-room.dto.ts
  backend/src/room/dto/reaction.dto.ts
  backend/src/room/dto/room.dto.ts
  backend/src/room/room.controller.ts
  backend/src/room/room.entity.ts
  backend/src/room/room.gateway.ts
  backend/src/room/room.repository.ts
  backend/src/room/services/room-create.service.ts
  backend/src/room/services/room-host.service.ts
  backend/src/room/services/room-join.service.ts
  backend/src/room/services/room-leave.service.ts
  frontend/src/components/common/Select.tsx
  frontend/src/components/session/SessionHeader.tsx
  frontend/src/components/session/SessionSidebar.tsx
  frontend/src/components/session/SessionToolbar.tsx
  frontend/src/components/sessions/create/SessionForm/index.tsx
  frontend/src/components/sessions/list/SessionList.tsx
  frontend/src/hooks/session/usePeerConnection.ts
  frontend/src/hooks/session/useReaction.ts
  frontend/src/hooks/session/useSession.ts
  frontend/src/hooks/session/useSocketEvents.ts
  frontend/src/hooks/type/session.d.ts
  frontend/src/pages/SessionPage.tsx
Labels: 🎁 Refactoring

#234 [Feat] 질문지 스크랩 기능(조회, 스크랩, 스크랩 취소) 구현
  backend/src/question-list/question-list.controller.ts
  backend/src/question-list/question-list.entity.ts
  backend/src/question-list/question-list.module.ts
  backend/src/question-list/question-list.repository.ts
  backend/src/question-list/question-list.service.ts
  backend/src/question-list/question.entity.ts
  backend/src/user/dto/user.dto.ts
  backend/src/user/user.entity.ts
Labels: ✨ Feature

#255 [Fix] index already exists 문제 해결 (패키지 출시함)
  backend/package.json
  backend/src/app.module.ts
  backend/src/main.ts
  backend/src/room/room.entity.ts
  backend/src/room/room.module.ts
  backend/src/room/room.repository.ts
  backend/src/websocket/websocket.entity.ts
  backend/src/websocket/websocket.module.ts
  backend/src/websocket/websocket.repository.ts
  pnpm-lock.yaml
Labels: 🐛 Bug Fix

#254 [Feat] 질문지 조회 기능에 Pagination 구현
  backend/package.json
  backend/src/question-list/dto/my-question-list.dto.ts
  backend/src/question-list/question-list.controller.ts
  backend/src/question-list/question-list.repository.ts
  backend/src/question-list/question-list.service.ts
Labels: ✨ Feature

#257 [Refactor] WebRTC DataChannel로 마이크,비디오 OnOff 상태 공유 기능 구현 ,세션 페이지 레이아웃 화면 안넘치게 조정 외 UX 개선
  frontend/public/assets/spinner.lottie
  frontend/src/components/common/LoadingIndicator.tsx
  frontend/src/components/session/DisplayMediaStream.tsx
  frontend/src/components/session/SessionHeader.tsx
  frontend/src/components/session/SessionSidebar.tsx
  frontend/src/components/session/SessionToolbar.tsx
  frontend/src/components/session/VideoContainer.tsx
  frontend/src/hooks/session/useMediaDevices.ts
  frontend/src/hooks/session/usePeerConnection.ts
  frontend/src/hooks/session/useReaction.ts
  frontend/src/hooks/session/useSession.ts
  frontend/src/hooks/session/useSocketEvents.ts
  frontend/src/index.css
  frontend/src/pages/SessionPage.tsx
Labels: 🎁 Refactoring

#256 [Feat] 스터디 기능을 위한 웹소켓 API 추가
  backend/src/room/dto/move-index.dto.ts
  backend/src/room/dto/room-id.dto.ts
  backend/src/room/dto/room.dto.ts
  backend/src/room/room.entity.ts
  backend/src/room/room.events.ts
  backend/src/room/room.gateway.ts
  backend/src/room/room.repository.ts
  backend/src/room/services/room-create.service.ts
  backend/src/room/services/room-join.service.ts
  backend/src/room/services/room.service.ts
Labels: ✨ Feature

#258 [Refactor] 마이페이지 카드 디자인 수정 | 모달창 개선 | 폴더 구조 일부 리팩토링 제안 | 리액트 쿼리 훅
  frontend/src/api/questions/createQuestionList.ts
  frontend/src/api/questions/deleteQuestionList.ts
  frontend/src/api/questions/editQuestionMetadata.ts
  frontend/src/api/questions/getQuestionContent.ts
  frontend/src/api/questions/getQuestionList.ts
  frontend/src/components/common/Button/index.tsx
  frontend/src/components/common/Modal/index.tsx
  frontend/src/components/common/PageTitle.tsx
  frontend/src/components/layout/SidebarPageLayout.tsx
  frontend/src/components/mypage/ButtonSection.tsx
  frontend/src/components/mypage/CategoryTab/Category.tsx
  frontend/src/components/mypage/CategoryTab/index.tsx
  frontend/src/components/mypage/Profile/index.tsx
  frontend/src/components/mypage/ProfileEditModal/ButtonSection.tsx
  frontend/src/components/mypage/ProfileIcon.tsx
  frontend/src/components/mypage/QuestionList/QuestionItem/Category.tsx
  frontend/src/components/mypage/QuestionList/QuestionItem/index.tsx
  frontend/src/components/mypage/QuestionList/index.tsx
  frontend/src/components/mypage/QuestionSection/QuestionList/QuestionItem/index.tsx
  frontend/src/components/mypage/QuestionSection/QuestionList/index.tsx
  frontend/src/components/questions/create/QuestionForm/index.tsx
  frontend/src/components/questions/detail/ButtonSection.tsx/index.tsx
  frontend/src/components/questions/detail/QuestionList.tsx/index.tsx
  frontend/src/components/questions/detail/QuestionTitle.tsx/index.tsx
  frontend/src/hooks/api/useCreateQuestionList.ts
  frontend/src/hooks/api/useDeleteQuestionList.ts
  frontend/src/hooks/api/useGetQuestionContent.ts
  frontend/src/hooks/api/useGetQuestionList.ts
  frontend/src/hooks/useAuth.ts
  frontend/src/hooks/useModal.ts
  frontend/src/pages/MyPage.tsx
  frontend/src/pages/MyPage/index.tsx
  frontend/src/pages/MyPage/view/Profile.tsx
  frontend/src/pages/MyPage/view/ProfileEditModal.tsx
  frontend/src/pages/MyPage/view/QuestionSection.tsx
  frontend/src/pages/MyPage/view/index.tsx
  frontend/src/pages/QuestionDetailPage.tsx
  frontend/src/routes.tsx
Labels: 🎁 Refactoring

#260 #260-1 [Feat] 유저 메타데이터 관련 API 추가
  backend/src/user/dto/update-user.dto.ts
  backend/src/user/dto/user.dto.ts
  backend/src/user/user.controller.ts
  backend/src/user/user.entity.ts
  backend/src/user/user.repository.ts
  backend/src/user/user.service.ts
Labels: ✨ Feature

#262 [Feat] 질문지 수정, 삭제 / 질문 추가, 수정, 삭제 구현
  backend/src/config/typeorm.config.ts
  backend/src/question-list/dto/delete-question.dto.ts
  backend/src/question-list/dto/question.dto.ts
  backend/src/question-list/dto/update-question-list.dto.ts
  backend/src/question-list/question-list.controller.ts
  backend/src/question-list/question-list.entity.ts
  backend/src/question-list/question-list.repository.ts
  backend/src/question-list/question-list.service.ts
Labels: ✨ Feature

#265 [Fix] 백엔드 리팩토링에 맞춰 테스트 코드 수정
  frontend/src/components/common/Modal/index.tsx
  frontend/src/components/mypage/QuestionList/QuestionItem/index.tsx
  frontend/src/hooks/__test__/useSession.test.ts
  frontend/src/hooks/session/usePeerConnection.ts
  frontend/src/hooks/session/useReaction.ts
  frontend/src/hooks/session/useSession.ts
  frontend/src/hooks/session/useSocketEvents.ts
  frontend/src/hooks/useAuth.ts
  frontend/src/hooks/useModal.ts
  frontend/src/pages/MyPage/view/Profile.tsx
  frontend/src/pages/MyPage/view/ProfileEditModal.tsx
Labels: 🐛 Bug Fix

#266 [Fix] 질문 삭제 로직에 transactional() 추가
  backend/src/question-list/question-list.service.ts
Labels: 🐛 Bug Fix

#281 [Feat] 스터디 기능 구현 | 스터디 시작 및 중지, 질문 넘기기, 사이드바 접기 구현, 진행 중인 세션에 대한 처리
  frontend/src/components/session/SessionHeader.tsx
  frontend/src/components/session/SessionSidebar.tsx
  frontend/src/components/session/Sidebar/SessionSidebar.tsx
  frontend/src/components/session/Sidebar/SidebarContainer.tsx
  frontend/src/components/session/Toolbar/CommonTools.tsx
  frontend/src/components/session/Toolbar/HostOnlyTools.tsx
  frontend/src/components/session/Toolbar/SessionToolbar.tsx
  frontend/src/constants/WebSocket/StudyEvent.ts
  frontend/src/hooks/session/useSession.ts
  frontend/src/hooks/session/useSocketEvents.ts
  frontend/src/hooks/session/useStudy.ts
  frontend/src/hooks/type/session.d.ts
  frontend/src/index.css
  frontend/src/pages/SessionPage.tsx
Labels: ✨ Feature, 스터디 기능

#282 [Feat] 마이페이지 질문지 탭 실제 api 연결 및 리액트 쿼리 훅으로 분리해서 사용
  frontend/src/api/question-list/createQuestionList.ts
  frontend/src/api/question-list/deleteQuestionList.ts
  frontend/src/api/question-list/editQuestionMetadata.ts
  frontend/src/api/question-list/getMyQuestionList.ts
  frontend/src/api/question-list/getQuestionContent.ts
  frontend/src/api/question-list/getQuestionList.ts
  frontend/src/api/question-list/getScrapQuestionList.ts
  frontend/src/api/questions/getQuestionContent.ts
  frontend/src/components/mypage/QuestionList/QuestionItem/index.tsx
  frontend/src/components/mypage/QuestionList/index.tsx
  frontend/src/components/sessions/create/SessionForm/ListSelectModal/index.tsx
  frontend/src/components/sessions/create/SessionForm/QuestionListSection/index.tsx
  frontend/src/components/sessions/create/SessionForm/index.tsx
  frontend/src/hooks/__test__/useSession.test.ts
  frontend/src/hooks/api/useCreateQuestionList.ts
  frontend/src/hooks/api/useDeleteQuestionList.ts
  frontend/src/hooks/api/useGetMyQuestionList.ts
  frontend/src/hooks/api/useGetQuestionContent.ts
  frontend/src/hooks/api/useGetQuestionList.ts
  frontend/src/hooks/api/useGetScrapQuestionList.ts
  frontend/src/pages/MyPage/view/Profile.tsx
  frontend/src/pages/MyPage/view/QuestionSection.tsx
  frontend/src/pages/MyPage/view/index.tsx
Labels: ✨ Feature

#283 [Fix] 프론트엔드 빌드 오류 수정
  frontend/src/components/questions/detail/QuestionList.tsx/index.tsx
  frontend/src/components/questions/detail/QuestionTitle.tsx/index.tsx
  frontend/src/components/session/Sidebar/SessionSidebar.tsx
  frontend/src/hooks/__test__/useSession.test.ts
  frontend/src/pages/QuestionDetailPage.tsx
Labels: 🐛 Bug Fix

#287 [Feat] 세션 리스트 API 에 질문지 이름 항목 추가
  backend/src/room/dto/room-list.dto.ts
  backend/src/room/dto/room.dto.ts
  backend/src/room/room.entity.ts
  backend/src/room/room.repository.ts
  backend/src/room/services/room-create.service.ts
  backend/src/room/services/room.service.ts
Labels: ✨ Feature

#288 [Refactor] 세션 리스트 페이지 리팩토링
  frontend/public/assets/notfound.lottie
  frontend/src/api/config/axios.ts
  frontend/src/api/session-list/getSessionList.ts
  frontend/src/components/common/Animate/NotFound.tsx
  frontend/src/components/common/CreateButton.tsx
  frontend/src/components/common/Divider.tsx
  frontend/src/components/common/Error/ErrorBlock.tsx
  frontend/src/components/common/SearchBar.tsx
  frontend/src/components/layout/ProtectedRouteLayout.tsx
  frontend/src/components/layout/SidebarPageLayout.tsx
  frontend/src/components/sessions/SessionCard.tsx
  frontend/src/hooks/session/useStudy.ts
  frontend/src/index.css
  frontend/src/pages/CreateQuestionPage.tsx
  frontend/src/pages/QuestionListPage.tsx
  frontend/src/pages/SessionListPage.tsx
  frontend/src/pages/SessionListPage/SessionListPage.tsx
  frontend/src/pages/SessionListPage/api/useGetSessionList.ts
  frontend/src/pages/SessionListPage/types/session.d.ts
  frontend/src/pages/SessionListPage/view/SessionCard.tsx
  frontend/src/pages/SessionListPage/view/list/SessionList.tsx
  frontend/src/routes.tsx
  frontend/tailwind.config.js
Labels: 🎁 Refactoring

#289 [Feat] 스터디 세션 생성 시 사용량 업데이트 로직 추가
  backend/src/room/services/room-create.service.ts
Labels: ✨ Feature, 스터디 세션 기능
